# Where the homeserver's Client-Server API is located. Typically this
# is where clients would be connecting to in order to send messages.
homeserverUrl: "https://matrix.org"

# An access token for the bot to use. Learn how to get an access token
# at https://t2bot.io/docs/access_tokens
accessToken: "YOUR_TOKEN_HERE"

# Whether or not to autojoin rooms when invited.
autoJoin: true

# Location on disk for where to store various bot information.
dataPath: "storage"

# The event types the bot will check for in the power levels to determine
# if the user can do something. These are all assumed to be state events.
# The events themselves do not have to exist, though if you want to change
# which power level is required they need to be defined in the m.room.power_levels
permissionCheck:
  # The permission check for creating/updating reminders in a room.
  roomReminders: "io.t2bot.ics_reminders"
